#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1

#SBATCH --job-name=M5a5F1
#SBATCH --output=outputs_exps/slurm_runtime/slurm_runtime_%x.%j.out
#SBATCH --error=outputs_exps/slurm_runtime/slurm_runtime_%x.%j.err

if [[ $# < 2 ]]
then
    echo "usage: sbatch exp_TEST matrix block_size"
else

matrix=$1
block_size=$2

echo "$matrix" | sed 's|.*/||' | cut -d'.' -f1 > name.tmp
matnum=$(<name.tmp)
echo $matnum

tmp=$( echo "l($block_size) / l(2) -2" | bc -l )
col=${tmp%.*}
echo "col = $col"
tau=$(grep $matnum tau.csv | cut -d, -f $col)
echo "tau = $tau"

if [[ $# > 2 ]]
then
    cval=$3
else
    cval=1024
fi
echo "cval = $cval"

if [[ $# > 3 ]]
then
    Sval=$4
else
    Sval=1024
fi
echo "Sval = $Sval"

 ./programs/cuda/cuda_multiply -b $block_size -a 5 -t $tau -F 1 -P 1 -B $block_size -f $matrix -v 1 -M 5 -c $cval -S $Sval > outputs_exps/M5a5F1_$matnum-$block_size-$cval.out 2> outputs_exps/M5a5F1_$matnum-$block_size-$cval.err

fi
