#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --partition=short
#SBATCH --gres=gpu:1

#SBATCH --job-name=BellMult
#SBATCH --output=outputs_exps/slurm_runtime_%x.%j.out
#SBATCH --error=outputs_exps/slurm_runtime_%x.%j.err

if [[ $# < 2 ]]
then
    echo "usage: sbatch exp_TEST matrix block_size"
else

matrix=$1
block_size=$2

echo "$matrix" | sed 's|.*/||' | cut -d'.' -f1 > name.tmp
matnum=$(<name.tmp)
echo $matnum

 ./programs/cuda/cuda_multiply -b $block_size -a 2 -F 1 -P 1 -B $block_size -f $matrix -v 1 -M 3 > outputs_exps/BellMult_$matnum-$block_size.out 2> outputs_exps/BellMult_$matnum-$block_size.err

fi
