#!/bin/bash

#SBATCH --job-name=exp_6
#SBATCH --ntasks=1
#SBATCH --partition=short
#SBATCH --gres=gpu:1

#SBATCH --output=outputs_exps/exp_6.out
#SBATCH --error=outputs_exps/exp_6.err

./programs/cuda/cuda_multiply -b 32 -a 5 -t 0.3 -F 1 -P 1 -B 32 -f data/real_world/wiki-Vote_r.el -v 1 -M 4
