#!/bin/bash

#SBATCH --job-name=exp_5
#SBATCH --ntasks=1
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1

#SBATCH --output=outputs_exps/slurm_runtime/slurm_runtime_%x_%j.out
#SBATCH --error=outputs_exps/slurm_runtime/slurm_runtime_%x_%j.err

if [[ $# < 2 ]]
then
    echo "usage: sbatch exp_TEST matrix block_size"
else

matrix=$1
block_size=$2

if [[ $# > 2 ]]
then
    cval=$3
else
    cval=1024
fi
echo "cval = $cval"

echo "$matrix" | sed 's|.*/||' | cut -d'.' -f1 > name.tmp
matnum=$(<name.tmp)
echo $matnum

./programs/cuda/cuda_multiply -b $block_size -a 4 -t 0.3 -F 1 -P 1 -B $block_size -f $matrix -v 1 -M 4 -c $cval > outputs_exps/exp_5_$matnum-$block_size-$cval.out 2> outputs_exps/exp_5_$matnum-$block_size-$cval.err

fi
