#!/bin/bash

#SBATCH --job-name=exp_3
#SBATCH --ntasks=1
#SBATCH --partition=short
#SBATCH --gres=gpu:1

#SBATCH --output=outputs_exps/slurm_runtime_%x_%j.out
#SBATCH --error=outputs_exps/slurm_runtime_%x_%j.err

if [[ $# < 2 ]]
then
    echo "usage: sbatch exp_TEST matrix block_size"
else

matrix=$1
block_size=$2

if [[ $# > 2 ]]
then
    cval=$3
else
    cval=1024
fi
echo "cval = $cval"

echo "$matrix" | sed 's|.*/||' | cut -d'.' -f1 > name.tmp
matnum=$(<name.tmp)
echo $matnum

./programs/cuda/cuda_multiply -b $block_size -a 5 -t 0.3 -F 1 -P 1 -B $block_size -f $matrix -v 1 -M 3 -c $cval > outputs_exps/exp_3_$matnum-$block_size-$3.out 2> outputs_exps/exp_3_$matnum-$block_size-$3.err

fi
