#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --partition=short
#SBATCH --gres=gpu:1

#SBATCH --job-name=VbrNoFix
#SBATCH --output=outputs_exps/slurm_runtime_%x.%j.out
#SBATCH --error=outputs_exps/slurm_runtime_%x.%j.err

if [[ $# < 2 ]]
then
    echo "usage: sbatch exp_TEST matrix block_size"
else

matrix=$1
block_size=$2

echo "$matrix" | sed 's|.*/||' | cut -d'.' -f1 > name.tmp
matnum=$(<name.tmp)
echo $matnum

 ./programs/cuda/cuda_multiply -b $block_size -a 4 -t 0.7 -P 1 -f $matrix -v 1 -M 4 > outputs_exps/VbrNoFix_$matnum-$block_size.out 2> outputs_exps/VbrNoFix_$matnum-$block_size.err

fi
